// The label of every control the Row, Column and Table pill menus render, in
// the order the popup renders them. Two suites read this list: the unit test
// beside the menus (src/table-size-buttons.menu-items.test.ts), which describes
// what each item does, and the end-to-end spec (tests/e2e/pill-menus.spec.ts),
// which clicks each item where a real browser draws it. Keeping one list means
// an item added to a menu and to only one of the two suites fails the other.

export type PillMenu = "row" | "column" | "table";

export const kRowMenuLabels: string[] = [
  "Add Row Above",
  "Add Row Below",
  "Move Row Up",
  "Move Row Down",
  "Grow",
  "Hug",
  "Fixed size",
  "Text",
  "Table",
  "Image",
  "Video",
  "Left",
  "Center",
  "Right",
  "Padding between border and text",
  "Fill",
  "Border color",
  "None",
  "Solid",
  "Dashed",
  "Dotted",
  "Double",
  "0 (None)",
  "1",
  "2",
  "4",
  "Corner radius 0",
  "Corner radius 4",
  "Corner radius 8",
  "Corner radius 16",
  "Paint format",
  "Duplicate Row",
  "Delete Row",
];

export const kColumnMenuLabels: string[] = [
  "Add Column Left",
  "Add Column Right",
  "Move Left",
  "Move Right",
  "Grow",
  "Hug",
  "Fixed size",
  "Text",
  "Table",
  "Image",
  "Video",
  "Left",
  "Center",
  "Right",
  "Padding between border and text",
  "Fill",
  "Border color",
  "None",
  "Solid",
  "Dashed",
  "Dotted",
  "Double",
  "0 (None)",
  "1",
  "2",
  "4",
  "Corner radius 0",
  "Corner radius 4",
  "Corner radius 8",
  "Corner radius 16",
  "Paint format",
  "Duplicate Column",
  "Delete Column",
];

export const kTableMenuLabels: string[] = [
  "Text",
  "Table",
  "Image",
  "Video",
  "Left",
  "Center",
  "Right",
  "Padding between border and text",
  "Fill",
  "Border color",
  "None",
  "Solid",
  "Dashed",
  "Dotted",
  "Double",
  "0 (None)",
  "1",
  "2",
  "4",
  "Corner radius 0",
  "Corner radius 4",
  "Corner radius 8",
  "Corner radius 16",
  "Horizontal space between cells",
  "Vertical space between cells",
  "Copy properties",
  "Paste properties",
  "Copy Table",
  "Cut Table",
  "Delete Table",
];

export const kPillMenuLabels: Record<PillMenu, string[]> = {
  row: kRowMenuLabels,
  column: kColumnMenuLabels,
  table: kTableMenuLabels,
};
